### ISSUE TITLE
Is possible to use this theme with vscode extension preview feature?

### ISSUE THREAD

**Issue by 6a6f6a6f** [dgisolfi/marp#1]
I'm trying to make the extension to follow the location of `dracula.css` but without success. My current file structure is:

```
.
├── assets
├── dracula.css
└── index.md
```

There is some hack to made this work?

**Comment by yhatt** [comment]
Hi, I'm the author of Marp.

In the case of VS Code extension, you have to set the path to CSS in the extension setting. Unlike CLI, it allows remote URL so you can use the recent dracula theme without downloading CSS file by setting [raw address of GitHub](https://raw.githubusercontent.com/dracula/marp/master/dracula/dracula.css).

![](https://user-images.githubusercontent.com/3993388/124719924-9a084180-df42-11eb-8ba8-f5041e6b688d.png)

```jsonc
// settings.json
{
  "markdown.marp.themes": [
    "https://raw.githubusercontent.com/dracula/marp/master/dracula/dracula.css"
  ],
}
```

That's all. VS Code recognizes dracula custom theme:

![](https://user-images.githubusercontent.com/3993388/124720222-e18ecd80-df42-11eb-88c3-0651a6adad8a.png)

**Comment by 6a6f6a6f** [comment]
Thank you @yhatt!
